name: Staging Environment
description: Staging deployment environment

# Branch protection rules
protection_rules:
  - pattern: staging/*
  - pattern: release/*

env:
  url: https://staging.complicesconecta.com
  NEXT_PUBLIC_API_URL: https://api-staging.complicesconecta.com

# Secrets requeridos
secrets:
  - name: VERCEL_TOKEN
    description: Token de acceso a Vercel
    required: true
  - name: VERCEL_ORG_ID
    description: ID de la organización en Vercel
    required: true
  - name: VERCEL_PROJECT_ID
    description: ID del proyecto en Vercel
    required: true
