name: Verificación de Dependencias y Pruebas de Construcción

on:
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        app: ['web', 'mobile']

    steps:
    - uses: actions/checkout@v5

    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'


    - name: Configurar caché npm
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-cache-

    - name: Instalar Dependencias
      run: npm install --omit=optional

    - name: Verificación de Tipos
      run: npx tsc --noEmit

    - name: Prueba de Construcción
      run: npm run build

    - name: Ejecutar Pruebas
      run: npm test
      continue-on-error: true
